name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build, tag, and push image to Amazon ECR
      run: echo Setting Vars for Testing
      env:
        ECR_REGISTRY: my-registry
        ECR_REPOSITORY: mytunes-downloader
        IMAGE_TAG: ${{ github.sha }}

    - name: Run a multi-line script
      run: |
        echo Following is the Payload
        echo '{ "image_uri": "${ECR_REGISTRY}/${ECR_REPOSITORY}:${env.IMAGE_TAG}" }''
